apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game
spec:
  ports:
    - name: grpc
      port: 8201
      targetPort: 8201
    - name: debug
      port: 8202
      targetPort: 8202
  selector:
    app: game
