apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: grpc
      port: 8001
      targetPort: 8001
      nodePort: 32765
    - name: debug
      port: 8002
      targetPort: 8002
  selector:
    app: gateway
  type: NodePort
