---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-login",
            "image": "busybox",
	    "imagePullPolicy": "Always",
            "command": ["sh", "-c", "until nslookup login; do echo waiting for chat; sleep 2; done;"]
          },
          {
            "name": "init-auth",
            "image": "busybox",
	    "imagePullPolicy": "Always",
            "command": ["sh", "-c", "until nslookup auth; do echo waiting for chat; sleep 2; done;"]
          },
          {
            "name": "init-game",
            "image": "busybox",
	    "imagePullPolicy": "Always",
            "command": ["sh", "-c", "until nslookup game; do echo waiting for chat; sleep 2; done;"]
          },
          {
            "name": "init-chat",
            "image": "busybox",
	    "imagePullPolicy": "Always",
            "command": ["sh", "-c", "until nslookup chat; do echo waiting for chat; sleep 2; done;"]
          }
        ]'
    spec:
      containers:
      - name: gateway
        image: ctxswh/gateway:1.0.0
        command:
          - "/gateway"
        args:
          - "-stderrthreshold=INFO"
          - "-port=8001"
          - "-debugPort=8002"
          - "-cert=/gatewaytls/server.pem"
          - "-key=/gatewaytls/server-key.pem"
          - "-authServerAddr=auth:8101"
          - "-gameServerAddr=game:8201"
          - "-chatServerAddr=chat:8301"
          - "-loginServerAddr=login:8401"
        ports:
          - name: grpc
            containerPort: 8001
          - name: debug
            containerPort: 8002
        volumeMounts:
          - name: "gatewaytls"
            readOnly: true
            mountPath: "/gatewaytls"
      volumes:
        - name: "gatewaytls"
          secret:
            secretName: "gatewaytls"
