apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: chat
spec:
  ports:
    - name: grpc
      port: 8301
      targetPort: 8301
    - name: debug
      port: 8302
      targetPort: 8302
  selector:
    app: chat
