apiVersion: v1
kind: ReplicationController
metadata:
  name: chat
spec:
  replicas: 3
  selector:
    app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: ctxswh/chat:1.0.0
        command:
          - "/chat"
        args:
          - "-stderrthreshold=INFO"  
          - "-port=8301"
          - "-debugPort=8302"
        ports:
          - name: grpc
            containerPort: 8301 
          - name: debug
            containerPort: 8302
