apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: grpc
      port: 8101
      targetPort: 8101
    - name: debug
      port: 8102
      targetPort: 8102
  selector:
    app: auth
