apiVersion: v1
kind: ReplicationController
metadata:
  name: login
spec:
  replicas: 1
  selector:
    app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ctxswh/login:1.0.0
        command:
          - "/login"
        args:
          - "-stderrthreshold=INFO"
          - "-port=8401"
          - "-httpPort=8402"
          - "-debugPort=8403"
        ports:
          - name: grpc 
            containerPort: 8401
          - name: http
            containerPort: 8402
          - name: debug
            containerPort: 8403
