apiVersion: v1
kind: Service
metadata:
  labels:
    app: login
  name: login
spec:
  ports:
    - name: grpc
      port: 8401 
      targetPort: 8401
    - name: http 
      port: 8402 
      nodePort: 32767 
      targetPort: 8402 
    - name: debug
      port: 8403 
      targetPort: 8403
  selector:
    app: login
  type: NodePort    
