apiVersion: v1
kind: ReplicationController
metadata:
  name: account
spec:
  replicas: 1
  selector:
    app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: ctxswh/account:1.0.0
        stdin: true
        tty: true
        volumeMounts:
          - name: "mysqltls"
            readOnly: true
            mountPath: "/mysqltls"
      volumes:
        - name: "mysqltls"
          secret:
            secretName: "mysqltls"
