// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

/*
Package gamepb is a generated protocol buffer package.

It is generated from these files:
	game.proto

It has these top-level messages:
	GameRequest
	GameResponse
*/
package gamepb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

import gatewaypb "github.com/williammuji/ctxswh/gatewaypb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameRequest struct {
	// Types that are valid to be assigned to MessageRequest:
	//	*GameRequest_PingpongRequest
	MessageRequest isGameRequest_MessageRequest `protobuf_oneof:"MessageRequest"`
}

func (m *GameRequest) Reset()                    { *m = GameRequest{} }
func (m *GameRequest) String() string            { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()               {}
func (*GameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isGameRequest_MessageRequest interface {
	isGameRequest_MessageRequest()
}

type GameRequest_PingpongRequest struct {
	PingpongRequest *gatewaypb.PingpongData `protobuf:"bytes,1,opt,name=pingpongRequest,oneof"`
}

func (*GameRequest_PingpongRequest) isGameRequest_MessageRequest() {}

func (m *GameRequest) GetMessageRequest() isGameRequest_MessageRequest {
	if m != nil {
		return m.MessageRequest
	}
	return nil
}

func (m *GameRequest) GetPingpongRequest() *gatewaypb.PingpongData {
	if x, ok := m.GetMessageRequest().(*GameRequest_PingpongRequest); ok {
		return x.PingpongRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameRequest_OneofMarshaler, _GameRequest_OneofUnmarshaler, _GameRequest_OneofSizer, []interface{}{
		(*GameRequest_PingpongRequest)(nil),
	}
}

func _GameRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameRequest)
	// MessageRequest
	switch x := m.MessageRequest.(type) {
	case *GameRequest_PingpongRequest:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingpongRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameRequest.MessageRequest has unexpected type %T", x)
	}
	return nil
}

func _GameRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameRequest)
	switch tag {
	case 1: // MessageRequest.pingpongRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gatewaypb.PingpongData)
		err := b.DecodeMessage(msg)
		m.MessageRequest = &GameRequest_PingpongRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameRequest)
	// MessageRequest
	switch x := m.MessageRequest.(type) {
	case *GameRequest_PingpongRequest:
		s := proto.Size(x.PingpongRequest)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GameResponse struct {
	// Types that are valid to be assigned to MessageResponse:
	//	*GameResponse_PingpongResponse
	MessageResponse isGameResponse_MessageResponse `protobuf_oneof:"MessageResponse"`
}

func (m *GameResponse) Reset()                    { *m = GameResponse{} }
func (m *GameResponse) String() string            { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()               {}
func (*GameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isGameResponse_MessageResponse interface {
	isGameResponse_MessageResponse()
}

type GameResponse_PingpongResponse struct {
	PingpongResponse *gatewaypb.PingpongData `protobuf:"bytes,1,opt,name=pingpongResponse,oneof"`
}

func (*GameResponse_PingpongResponse) isGameResponse_MessageResponse() {}

func (m *GameResponse) GetMessageResponse() isGameResponse_MessageResponse {
	if m != nil {
		return m.MessageResponse
	}
	return nil
}

func (m *GameResponse) GetPingpongResponse() *gatewaypb.PingpongData {
	if x, ok := m.GetMessageResponse().(*GameResponse_PingpongResponse); ok {
		return x.PingpongResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameResponse_OneofMarshaler, _GameResponse_OneofUnmarshaler, _GameResponse_OneofSizer, []interface{}{
		(*GameResponse_PingpongResponse)(nil),
	}
}

func _GameResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameResponse)
	// MessageResponse
	switch x := m.MessageResponse.(type) {
	case *GameResponse_PingpongResponse:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingpongResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameResponse.MessageResponse has unexpected type %T", x)
	}
	return nil
}

func _GameResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameResponse)
	switch tag {
	case 1: // MessageResponse.pingpongResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gatewaypb.PingpongData)
		err := b.DecodeMessage(msg)
		m.MessageResponse = &GameResponse_PingpongResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameResponse)
	// MessageResponse
	switch x := m.MessageResponse.(type) {
	case *GameResponse_PingpongResponse:
		s := proto.Size(x.PingpongResponse)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*GameRequest)(nil), "gamepb.GameRequest")
	proto.RegisterType((*GameResponse)(nil), "gamepb.GameResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameService service

type GameServiceClient interface {
	Serve(ctx context.Context, opts ...grpc.CallOption) (GameService_ServeClient, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Serve(ctx context.Context, opts ...grpc.CallOption) (GameService_ServeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameService_serviceDesc.Streams[0], c.cc, "/gamepb.GameService/Serve", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceServeClient{stream}
	return x, nil
}

type GameService_ServeClient interface {
	Send(*GameRequest) error
	Recv() (*GameResponse, error)
	grpc.ClientStream
}

type gameServiceServeClient struct {
	grpc.ClientStream
}

func (x *gameServiceServeClient) Send(m *GameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceServeClient) Recv() (*GameResponse, error) {
	m := new(GameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GameService service

type GameServiceServer interface {
	Serve(GameService_ServeServer) error
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_Serve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).Serve(&gameServiceServeServer{stream})
}

type GameService_ServeServer interface {
	Send(*GameResponse) error
	Recv() (*GameRequest, error)
	grpc.ServerStream
}

type gameServiceServeServer struct {
	grpc.ServerStream
}

func (x *gameServiceServeServer) Send(m *GameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceServeServer) Recv() (*GameRequest, error) {
	m := new(GameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gamepb.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Serve",
			Handler:       _GameService_Serve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}

func init() { proto.RegisterFile("game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0xa4, 0xe4, 0x92, 0x4b,
	0x2a, 0x8a, 0xcb, 0x33, 0xf4, 0xd3, 0x13, 0x4b, 0x52, 0xcb, 0x13, 0x2b, 0x0b, 0x92, 0x60, 0x2c,
	0x88, 0x3a, 0xa5, 0x14, 0x2e, 0x6e, 0xf7, 0xc4, 0xdc, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x67, 0x2e, 0xfe, 0x82, 0xcc, 0xbc, 0xf4, 0x82, 0xfc, 0xbc, 0x74, 0xa8, 0x90, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb8, 0x1e, 0xdc, 0x04, 0xbd, 0x00, 0xa8, 0x0a, 0x97, 0xc4,
	0x92, 0x44, 0x0f, 0x86, 0x20, 0x74, 0x1d, 0x4e, 0x02, 0x5c, 0x7c, 0xbe, 0xa9, 0xc5, 0xc5, 0x89,
	0xe9, 0x30, 0x63, 0x95, 0x32, 0xb8, 0x78, 0x20, 0xb6, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a,
	0xb9, 0x72, 0x09, 0x20, 0x34, 0x41, 0xc4, 0x08, 0xdb, 0x83, 0xa1, 0xc5, 0x49, 0x90, 0x8b, 0x1f,
	0x6e, 0x11, 0x44, 0xc8, 0xc8, 0x1d, 0xe2, 0x9f, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21,
	0x0b, 0x2e, 0x56, 0x10, 0x33, 0x55, 0x48, 0x58, 0x0f, 0x12, 0x20, 0x7a, 0x48, 0xbe, 0x95, 0x12,
	0x41, 0x15, 0x84, 0x18, 0xa1, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x1f, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x09, 0xde, 0x43, 0x55, 0x01, 0x00, 0x00,
}
